#
# NixOS Configuration for Work Machine
#
# This configuration represents a full development workstation with:
# - NVIDIA GPU support optimized for Wayland/Hyprland
# - Development services (MySQL, PostgreSQL, Redis, Elasticsearch)
# - Remote development support through VS Code Server
# - Security hardening through Falcon sensor
# - Network management and VPN connectivity
#

{
  inputs,
  lib,
  ezModules,
  config,
  pkgs,
  ...
}:
{
  #-----------------------------------------------------------------------------
  # MODULE IMPORTS
  #-----------------------------------------------------------------------------
  # These imports bring in both local and external configurations organized
  # by function. The imports use the 'with inputs' pattern to access flake inputs.

  imports = with inputs; [
    # Local hardware-specific configuration generated by nixos-generate-config
    ./hardware-configuration.nix

    # User configuration modules
    ezModules.root # Root user setup with secure defaults
    ezModules.seanhxx # Personal user with appropriate permissions

    # System functionality modules
    ezModules.misc # Miscellaneous system utilities
    ezModules.client-cli # Command-line tools for client system
    ezModules.gui # Graphical UI components and dependencies
    ezModules.core # Core system settings (locales, time, etc.)
    ezModules.greetd # Modern display manager for Wayland
    ezModules.virtualisation # VM and container support

    # Hardware-specific support for Lenovo Legion 16ACH6H
    # (AMD CPU + NVIDIA GPU gaming laptop)
    nixos-hardware.nixosModules.lenovo-legion-16ach6h

    # System optimization modules from SrvOS project
    srvos.nixosModules.desktop # Desktop environment optimizations
    srvos.nixosModules.mixins-trusted-nix-caches # Faster builds with trusted caches
    srvos.nixosModules.mixins-nix-experimental # Enable experimental Nix features
    srvos.nixosModules.mixins-tracing # Debugging and tracing support

    # Development and security modules
    vscode-server.nixosModules.default # Remote VSCode development support
    xiongchenyu6.nixosModules.falcon-sensor # CrowdStrike Falcon security agent
  ];

  #-----------------------------------------------------------------------------
  # SYSTEM CONFIGURATION AND SECRETS
  #-----------------------------------------------------------------------------
  # Define system identity tags and secrets management

  # Secret management for Falcon security sensor
  sops.secrets."falcon/cid" = {
    # The CID (Customer ID) required for Falcon sensor authentication
    # This is managed by sops-nix for secure storage
  };

  # System tags determine which conditional modules are enabled
  # These tags are used in other configuration files to enable/disable features
  system.nixos.tags = [
    "nvidia" # Enable NVIDIA-specific configurations in imported modules
    "gui" # Enable GUI/desktop environment support in imported modules
  ];

  #-----------------------------------------------------------------------------
  # HARDWARE CONFIGURATION
  #-----------------------------------------------------------------------------
  # Hardware-specific settings, focused on GPU and firmware

  hardware = {
    # Enable non-free firmware required by various devices
    enableRedistributableFirmware = true;

    # NVIDIA GPU configuration for optimal performance
    nvidia = {
      # Force full composition pipeline for smoother display and reduced tearing
      forceFullCompositionPipeline = true;

      # Enable kernel modesetting for better Wayland compatibility
      modesetting.enable = true;

      # Power management for extended battery life on mobile workstation
      powerManagement = {
        enable = true; # Enable power saving features
        finegrained = false; # Coarse-grained power management for stability
      };

      # Configuration for NVIDIA driver approach
      open = false; # Use proprietary drivers for better performance
      prime.offload.enable = false; # Don't use PRIME offloading (single GPU system)
    };
  };

  #-----------------------------------------------------------------------------
  # ENVIRONMENT CONFIGURATION
  #-----------------------------------------------------------------------------
  # System-wide environment variables and settings

  environment = {
    # Session variables needed for proper NVIDIA + Wayland operation
    sessionVariables = {
      # Fix for hardware cursors in Wayland compositors with NVIDIA
      WLR_NO_HARDWARE_CURSORS = "1";

      # Configure GPU acceleration for video and rendering
      LIBVA_DRIVER_NAME = "nvidia";
      GBM_BACKEND = "nvidia-drm";
      __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    };
  };

  #-----------------------------------------------------------------------------
  # BOOT CONFIGURATION
  #-----------------------------------------------------------------------------
  # Boot loader and early system startup settings

  boot = {
    # Use the latest kernel for best hardware support and performance
    kernelPackages = pkgs.linuxPackages_latest;

    # Enable support for running ARM64 binaries through emulation
    binfmt.emulatedSystems = [ "aarch64-linux" ];

    # Boot loader configuration using systemd-boot (simpler than GRUB)
    loader = {
      systemd-boot = {
        configurationLimit = 12; # Keep 12 generations for rollback
        enable = true;
      };

      # EFI boot configuration
      efi = {
        canTouchEfiVariables = true; # Allow direct EFI variable modification
        efiSysMountPoint = "/boot"; # Mount point for EFI system partition
      };
    };
  };

  #-----------------------------------------------------------------------------
  # NETWORKING CONFIGURATION
  #-----------------------------------------------------------------------------
  # Network interfaces, firewall, and connectivity settings

  networking =
    let
      # Extract hostname from directory path for consistency
      file-path = builtins.split "/" (toString ./.);
      hostName = lib.last file-path;
    in
    {
      # Set hostname based on directory name
      inherit hostName;

      # Firewall configuration
      firewall = {
        enable = true; # Temporarily disabled - consider enabling with proper rules

        # Allowed TCP ports for various services
        allowedTCPPorts = [
          22
        ];

        # Allowed UDP ports for various services
        allowedUDPPorts = [
        ];

      };

      # NetworkManager provides user-friendly network management
      networkmanager = {
        enable = true;
        wifi = {
          powersave = false; # Enable WiFi power saving for better battery life
        };
      };

      # IPv6 support
      enableIPv6 = true;

      # Use DHCP for address assignment (can be overridden by NetworkManager)
      useDHCP = lib.mkDefault true;
    };

  #-----------------------------------------------------------------------------
  # SECURITY SERVICES
  #-----------------------------------------------------------------------------
  # Services related to system security and monitoring

  services = {
    # CrowdStrike Falcon endpoint protection
    falcon-sensor = {
      enable = true;
      # Path to the Customer ID secret provided by CrowdStrike
      cidFile = config.sops.secrets."falcon/cid".path;
      # Debug level logging for troubleshooting
      traceLevel = "debug";
    };

    #-------------------------------------------------------------------------
    # DISPLAY AND SESSION MANAGEMENT
    #-------------------------------------------------------------------------
    # Configuration for login and graphical session

    # Modern and minimal display manager compatible with Wayland
    greetd = {
      settings = {
        # Default session to start after login
        initial_session = {
          user = "seanhxx"; # Auto-login user
          command = lib.mkDefault "Hyprland"; # Start Hyprland compositor by default
        };
      };
    };

    #-------------------------------------------------------------------------
    # DATABASE SERVICES
    #-------------------------------------------------------------------------
    # Relational and NoSQL databases for development

    # MySQL/MariaDB relational database
    mysql = {
      enable = true;
      package = pkgs.mysql80; # Use MySQL 8.0 specifically

      # Storage location for database files
      dataDir = "/var/lib/mysql";

      # User configuration for development access
      ensureUsers = [
        {
          name = "seanhxx";
          ensurePermissions = {
            "seanhxx.*" = "ALL PRIVILEGES"; # Full access to own databases
            "*.seanhxx" = "ALL PRIVILEGES";
          };
        }
      ];

      # Create default database for user
      ensureDatabases = [ "seanhxx" ];

      # Database server configuration
      settings = {
        mysqld = {
          # Character encoding for modern web applications
          character-set-server = "utf8mb4";
          collation-server = "utf8mb4_unicode_ci";

          # Performance settings for development workstation
          innodb_buffer_pool_size = "128M";
          max_connections = 100;

          # Security hardening
          local-infile = 0; # Disable potentially dangerous local file operations

          # Only listen on localhost for security
          bind-address = "127.0.0.1";
        };
      };
    };

    # PostgreSQL relational database
    postgresql = {
      enable = true;

      # User configuration
      ensureUsers = [
        {
          name = "seanhxx";
          ensureDBOwnership = true; # User owns their databases
          ensureClauses = {
            superuser = true; # Allow database administration
          };
        }
      ];

      # Create default database for user
      ensureDatabases = [ "seanhxx" ];
    };

    #-------------------------------------------------------------------------
    # NETWORKING AND VPN SERVICES
    #-------------------------------------------------------------------------
    # Connectivity and remote access tools

    # NetBird peer-to-peer VPN for secure remote connectivity
    netbird = {
      enable = true;
      # Default configuration uses auto-discovery and management server
    };

    #-------------------------------------------------------------------------
    # SEARCH AND ANALYTICS SERVICES
    #-------------------------------------------------------------------------
    # Search engines and data stores for development

    # Elasticsearch search engine and analytics database
    elasticsearch = {
      enable = true;
      package = pkgs.elasticsearch7; # Use version 7.x specifically

      # Development mode with single node
      single_node = true;

      # Cluster identification
      cluster_name = "work-cluster";

      # Network configuration for local-only access
      listenAddress = "127.0.0.1";
      port = 9200; # HTTP API port
      tcp_port = 9300; # Inter-node communication port

      # Additional plugins
      plugins = [
        pkgs.elasticsearch7Plugins.ingest-attachment # Document processing plugin
      ];

      # Java memory settings to limit resource usage
      extraJavaOptions = [
        "-Xms512m" # Initial heap size
        "-Xmx512m" # Maximum heap size
      ];

      # Additional Elasticsearch configuration
      extraConf = ''
        xpack.security.enabled: false
        path.logs: /var/log/elasticsearch
        discovery.seed_hosts: ["127.0.0.1"]
      '';
    };

    # Redis in-memory database/cache
    redis = {
      servers = {
        default = {
          enable = true;
          port = 6379;
          bind = "127.0.0.1"; # Listen only on localhost
          databases = 16; # Number of logical databases

          # Persistence configuration
          appendOnly = true; # Enable append-only file for durability
          appendFsync = "everysec"; # Sync to disk every second (balance of performance/safety)

          # Memory management settings
          settings = {
            "maxmemory" = "256mb"; # Memory limit
            "maxmemory-policy" = "allkeys-lru"; # Eviction policy: least recently used
          };
        };
      };
    };
  };

  #-----------------------------------------------------------------------------
  # USER HOME CONFIGURATION
  #-----------------------------------------------------------------------------
  # User-specific settings managed via home-manager

  home-manager = {
    users = {
      "seanhxx" = {
        programs = {
          # Waybar status bar configuration (modern Wayland status bar)
          waybar = {
            settings = {
              # Network module configuration
              network = {
                interface = "wlp4s0"; # WiFi interface name for network monitoring
              };
            };
          };
        };
      };
    };
  };
}
